### Listar produtos
GET https://localhost:7083/api/produto/listar

### Buscar produto por nome
GET https://localhost:7083/api/produto/buscar/Arroz1

### Cadastrar produto
POST https://localhost:7083/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Arroz"
}